FROM node:18-alpine as base

WORKDIR /app

COPY package*.json .
RUN npm install
COPY . .
RUN npm run build

FROM base as production
WORKDIR /app
COPY --from=build /app/build ./build
COPY package*.json .

RUN npm install --only=prod

CMD npm run start