version: '3.4'
services:
  db:
    container_name: db
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
    ports:
      - '${DATABASE_PORT}:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - express-network
  server:
    container_name: server
    env_file:
      - .env
    restart: 'no'
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '${APP_PORT}:${APP_PORT}'
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads
    networks:
      - express-network
networks:
  express-network:
    driver: bridge
